#!/usr/bin/env bash
set -euo pipefail

# Setting up the PATH environment
[ -s /opt/homebrew/bin/brew ] && eval "$(/opt/homebrew/bin/brew shellenv)"
[ -s /usr/local/bin/brew ] && eval "$(/usr/local/bin/brew shellenv)"

# This loads nvm (for users managing Node.js via nvm)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# This loads mise (.tool-versions specifies erlang/elixir versions)
eval "$(mise activate bash)"

BASE="$(pwd)"
export MIX_ENV=prod
export MIX_TARGET=ios

cd ../../

mix local.hex --force --if-missing
mix local.rebar --force --if-missing

if [ ! -d "deps/desktop" ]; then
  mix deps.get
fi

if [ -f "$BASE/TemplateApp/app.zip" ]; then
  rm "$BASE/TemplateApp/app.zip"
fi

mix release --overwrite
mix assets.deploy

cd "_build/ios_prod/rel/template_app"
zip -9r "$BASE/TemplateApp/app.zip" lib/ releases/ --exclude "*.so"
